### ISSUE TITLE
Minimize and Maximize buttons are not colored

### ISSUE THREAD

**Issue by jacksonff** [IDislikeChair/norddiscord-darker#1]
I don't know if it's something that needs to be enabled or a bug, but their colors are not shown (only the hover color). The same happens using izutsumi's CSS file (so it may be something on my side). I tried playing with the file and deleting the [aria-label] makes them colored but no matter what I do, the color is shared between the two buttons. I'm not a programmer so it was trial and error with no luck.

**Comment by IDislikeChair** [comment]
Are you using non-English language for your Discord? I suspect the bug has to do with `aria-label` changes with language setting. I will release a bandage fix soon.

**Comment by IDislikeChair** [comment]
fde7ca3f6065a10e2fcf71458f10434fa81784f5 should fix it. @jacksonff Can you check?

**Comment by jacksonff** [comment]
Yes, you were completely right. It was the language before but your new revision fixed it in my main language too. Thanks!
